theme:
    name: material
    features:
        #- navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
        - navigation.prune  # Only render visible navigation items, collapsing deeper levels
    logo: images/logo.svg
    palette:
        - scheme: slate
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
        - scheme: white
          primary: white
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode

    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right

    #custom_dir: "docs/_overrides"  # Overriding part of the HTML

site_name: circulax
site_description: A Differentiable, Functional Circuit Analyzer based on JAX.

edit_uri: ""

strict: false  # Don't allow warnings during the build process

extra_css:
  - stylesheets/extra.css

# extra_javascript:
#     - _static/mathjax.js
#     - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_javascript:
  - _static/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins:
    - search:
        separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
    - gen-files:
        scripts:
            - docs/gen_doc_stubs.py
    - mkdocs-jupyter:
        #include_source: True  # Optional: Shows the 'source' of the notebook
        ignore_h1_titles: True
        execute: True
        include_source: False
        remove_tag_config:
            remove_input_tags:
            - remove-input      # The tag you added to hide code but keep output
            - hide-input        # Optional: tag to just collapse it
            remove_cell_tags:
            - remove-cell       # Tag to remove both code AND output
        theme: dark
    - literate-nav:
        nav_file: SUMMARY.md
    - mkdocstrings:
        handlers:
            python:
                paths: [circulax]
                inventories:
                    - https://docs.jax.dev/en/latest/objects.inv
                    - https://docs.kidger.site/jaxtyping/objects.inv
                    - https://docs.python.org/3/objects.inv
                    - https://docs.xarray.dev/en/stable/objects.inv
                    - https://matplotlib.org/stable/objects.inv
                    - https://numpy.org/doc/stable/objects.inv
                    - https://pandas.pydata.org/docs/objects.inv
                    - https://python-markdown.github.io/objects.inv
                    - https://scipy.github.io/devdocs/objects.inv
                    - https://typing.readthedocs.io/en/latest/objects.inv
                    - https://www.mkdocs.org/objects.inv
                options:
                    docstring_options:
                    ignore_init_summary: true
                    docstring_section_style: table
                    docstring_style: google
                    filters: ["!^_"]
                    heading_level: 1
                    inherited_members: true
                    line_length: 88
                    merge_init_into_class: true
                    separate_signature: true
                    show_root_full_path: false
                    show_root_heading: true
                    show_signature_annotations: true
                    show_source: true
                    show_symbol_type_heading: true
                    show_symbol_type_toc: true
                    signature_crossrefs: true
                    summary: true

    - mkdocs_matplotlib

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.snippets:
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"
        toc_depth: 2
    - attr_list
    - footnotes
    - pymdownx.emoji
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.tabbed:
        alternate_style: true

hooks:
  - docs/hooks.py

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cdaunt
